# Generated by Django 6.0.2 on 2026-03-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_purok_alter_household_purok_delete_clearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household',
            name='purok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.purok'),
        ),
    ]
