# Generated by Django 6.0.2 on 2026-03-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_remove_servicetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residents.servicerequest'),
        ),
    ]
