# Generated by Django 6.0.2 on 2026-03-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_alter_household_purok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
