# Generated by Django 6.0.2 on 2026-03-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0015_resident_educational_attainment_resident_indigenous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='precinct',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='emergency_contact_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='purpose_for',
            field=models.CharField(blank=True, choices=[('Barangay Clearance', 'Barangay Clearance'), ('Local Employment', 'Local Employment'), ('Bank Requirement', 'Bank Requirement'), ('Postal ID', 'Postal ID'), ('Police Clearance', 'Police Clearance'), ('NBI Clearance', 'NBI Clearance'), ('Senior Citizen ID', 'Senior Citizen ID'), ('PSA', 'PSA'), ('First Time Job Seeker', 'First Time Job Seeker'), ('Other', 'Other (state)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='purpose_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='residency_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
