# Generated by Django 6.0.2 on 2026-03-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0020_create_resident_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_auto_matched',
            field=models.BooleanField(default=False),
        ),
    ]
