# Generated by Django 6.0.2 on 2026-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0031_userprofile_civil_status_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='business_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='business_nature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='business_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
