# Generated by Django 6.0.2 on 2026-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0032_servicerequest_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='deceased_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='deceased_relationship',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requestor_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requestor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
