# Generated by Django 6.0.2 on 2026-04-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0034_servicerequest_business_permit_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='address_barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='address_house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='address_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='address_street',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='permanent_address',
            field=models.BooleanField(default=True),
        ),
    ]
