# Generated by Django 6.0.2 on 2026-04-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0035_resident_address_barangay_resident_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='purok',
        ),
        migrations.DeleteModel(
            name='Purok',
        ),
    ]
