# Generated by Django 6.0.2 on 2026-04-24 09:19

from django.db import migrations, models


def migrate_service_request_workflow(apps, schema_editor):
    ServiceRequest = apps.get_model("residents", "ServiceRequest")
    Payment = apps.get_model("residents", "Payment")

    paid_request_ids = set(Payment.objects.values_list("service_request_id", flat=True))
    status_map = {
        "Submitted": "PENDING",
        "Under Review": "PENDING",
        "For Validation": "PENDING",
        "Processing": "PENDING",
        "Pending Requirements": "PENDING_REQUIREMENTS",
        "On Hold": "PENDING",
        "Ready for Release": "READY_FOR_RELEASE",
        "Released": "RELEASED",
        "Rejected": "REJECTED",
        "Cancelled": "REJECTED",
    }

    for service_request in ServiceRequest.objects.all():
        payment_required = "YES" if (service_request.fee or 0) > 0 else "NO"
        if payment_required == "NO":
            payment_status = "EXEMPT"
        elif service_request.id in paid_request_ids:
            payment_status = "PAID"
        else:
            payment_status = "PENDING"

        new_status = status_map.get(service_request.status, "PENDING")
        if new_status == "READY_FOR_RELEASE" and payment_required == "YES" and payment_status != "PAID":
            new_status = "WAITING_PAYMENT"

        if new_status == "RELEASED" and payment_required == "YES" and payment_status != "PAID":
            new_status = "READY_FOR_RELEASE"

        if new_status == "PENDING" and payment_required == "YES" and payment_status == "PAID":
            new_status = "APPROVED"

        service_request.payment_required = payment_required
        service_request.payment_status = payment_status
        service_request.status = new_status
        service_request.save(update_fields=["payment_required", "payment_status", "status"])


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0037_seed_portal_service_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='payment_required',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('EXEMPT', 'EXEMPT'), ('PAID', 'PAID')], default='EXEMPT', max_length=10),
        ),
        migrations.RunPython(migrate_service_request_workflow, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_REQUIREMENTS', 'Pending Requirements'), ('APPROVED', 'Approved'), ('WAITING_PAYMENT', 'Waiting Payment'), ('READY_FOR_RELEASE', 'Ready for Release'), ('RELEASED', 'Released'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
