# Generated by Django 6.0.2 on 2026-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0038_servicerequest_payment_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='free_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
