# Generated by Django 6.0.2 on 2026-03-13 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='household',
            name='purok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.purok'),
        ),
        migrations.DeleteModel(
            name='Clearance',
        ),
    ]
