# Generated by Django 6.0.2 on 2026-03-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_servicetype_fee_alter_household_purok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='description',
        ),
    ]
