# Generated by Django 6.0.2 on 2026-03-13 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_alter_servicerequest_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='purok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='residents.purok'),
        ),
    ]
