# Generated by Django 6.0.2 on 2026-03-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_servicerequest_created_by_alter_complaint_filed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
