# Generated by Django 6.0.2 on 2026-03-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0011_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='default_fee',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
