# Generated by Django 6.0.2 on 2026-03-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0014_alter_auditlog_options_auditlog_after_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='educational_attainment',
            field=models.CharField(blank=True, choices=[('', '---------'), ('No Formal Education', 'No Formal Education'), ('Elementary', 'Elementary'), ('High School', 'High School'), ('Vocational', 'Vocational'), ('College', 'College'), ('Postgraduate', 'Postgraduate')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resident',
            name='indigenous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='occupation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='solo_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
