# Generated by Django 6.0.2 on 2026-03-22 06:20

import django.db.models.deletion
from django.db import migrations, models


def seed_default_request_purposes(apps, schema_editor):
    RequestPurpose = apps.get_model('residents', 'RequestPurpose')
    defaults = [
        ("Barangay Clearance", False, 1),
        ("Local Employment", False, 2),
        ("Bank Requirement", False, 3),
        ("Postal ID", False, 4),
        ("Police Clearance", False, 5),
        ("NBI Clearance", False, 6),
        ("Senior Citizen ID", False, 7),
        ("PSA", False, 8),
        ("First Time Job Seeker", False, 9),
        ("Other (state)", True, 10),
    ]
    for name, requires_details, sort_order in defaults:
        RequestPurpose.objects.get_or_create(
            name=name,
            defaults={
                "requires_details": requires_details,
                "is_active": True,
                "sort_order": sort_order,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0016_resident_precinct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('requires_details', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='purpose_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='residents.requestpurpose'),
        ),
        migrations.RunPython(seed_default_request_purposes, migrations.RunPython.noop),
    ]
