# Generated by Django 6.0.2 on 2026-03-22 06:51

from django.db import migrations, models


def copy_existing_fee_to_new_fields(apps, schema_editor):
    ServiceType = apps.get_model('residents', 'ServiceType')
    for service_type in ServiceType.objects.all():
        service_type.voter_fee = service_type.fee
        service_type.non_voter_fee = service_type.fee
        service_type.save(update_fields=["voter_fee", "non_voter_fee"])


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0017_requestpurpose_servicerequest_purpose_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='non_voter_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='voter_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.RunPython(copy_existing_fee_to_new_fields, migrations.RunPython.noop),
    ]
