# Generated by Django 6.0.2 on 2026-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0021_userprofile_is_auto_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='valid_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='valid_ids/'),
        ),
    ]
